labelToAdd: "incomplete issue report"
labelsToCheck:
  - bug
commentHeader: "It looks like this issue is missing some information:"
requiredItems:
  - response: "- A [codepen](https://codepen.io/pen?template=RwgrjEx), [codesandbox](https://codesandbox.io/s/calcite-template-p95kp?file=/src/App.js), or [jsbin](https://jsbin.com/qecewik/edit?html,output) that reproduces the issue. Alternatively, a [documentation](https://developers.arcgis.com/calcite-design-system/components/) sample can be used if the issue is reproducible. If you are experiencing build or Node related errors, please provide a GitHub repo for the sample."
    requireAll: false
    content:
      - "jsbin.com/"
      - "codepen.io/"
      - "codesandbox.io/"
      - "esri.github.io/calcite-components/?path=/story/components-"
      - "esri.github.io/calcite-components/iframe.html?"
      - "developers.arcgis.com/calcite-design-system/components/"
      - "ember-twiddle.com/"
      - "jsfiddle.net/"
      - "github.com/"
      - "w3.org/WAI/"
commentFooter: "Issues without reproduction samples may not be prioritized. If you were unable to create a sample, please try to answer any questions that arise once development begins. Thanks for your understanding."
excludeComments: true
