labelToAdd: "incomplete issue report"
labelsToCheck:
  - bug
commentHeader: "More information is required to proceed with this issue:"
requiredItems:
  - response: "- Provide a [codepen](https://codepen.io/pen?template=RwgrjEx), [codesandbox](https://codesandbox.io/s/calcite-template-p95kp?file=/src/App.js), or [jsbin](https://jsbin.com/wiguxohisa/edit?html,output) that reproduces the issue. Alternatively, a [documentation](https://developers.arcgis.com/calcite-design-system/components/) sample can be used if the issue is reproducible."
    requireAll: false
    content:
      - "jsbin.com/"
      - "codepen.io/"
      - "codesandbox.io/"
      - "esri.github.io/calcite-components/?path=/story/components-"
      - "esri.github.io/calcite-components/iframe.html?"
      - "developers.arcgis.com/calcite-design-system/components/"
      - "ember-twiddle.com/"
      - "jsfiddle.net/"
commentFooter: "This issue will be automatically closed in five days if the information is not provided. Thanks for your understanding."
excludeComments: true
