branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "H0errC4q/+UwTxZPxF9ss1VP6T8GQD/rnhogdVf5tlFx32FRyov4HCuYkDx8NQOTT0uvCFVBs3XEVvpLssGCL8uBGkgPwdh7rT+reaCKHL7i7V9Jb4HA6Q+ZY3fKeYav1T67nqOgo+bGeXnZhlifDmPHrM0okIQst2uUVzimmhSJlNj4KjICYocMoREHbe6GqeSfA3M1+4K8TuKcxnQlwdnzZreCrJF/qfuF2FfGgv3GkOsxXY/Kg2TB5yUoCXUIXBagox4EWgqyTgEm7X+m8wQuN3v/lFfr5MoeKOL6M75VyYI/X+RE9BJ6FDSf8sai9KtKdTN6nbqohto69dgB7cBgXWQIuxm59+5cRudEaIrFTJpsTSWhAzNSfpC0e80JyV16K4bsf5fPizgQivhVbmmkAFvuM/LMFUAp3Lh5qmsX3b3hNS68CaZi+BRxYWFd6HKjb1LKuHzvr7sp2a06lChQxPRB09Pu8gxLZ3UJGOuUHFgSIUv9SyznMe02lhuPoklyqWnkHczUPFDvhOrOInrkCMItwy6x6CZM68uCaImD5IlnrMiOXHAb5fOgLI+cTj0PcRVCG0DlqLEjhLK3r/cq0fLegQx1lR5OLOJDPTiP+Tuj0/hGQoRHIjD9d4k3DJudH61+D+asPjDWWqkKs9ZYqKC6yGsusKhDiL5laHI="
script:
  - npm test
