branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "NmCqqWhKFtoNofWB8t09v6nTkUCrj5aWKV9/n4rNmdY7ee/gktqehR3P3zfJK1iSlvJ3ewgp/alqCpcgto1mM3QljHp5QAs3f9la8Klqihy5zrRp21N9nsdPJpgLlQd/FhWh5Ss+t0dJ/nPqSWH1j2kvFjjUK1fSxzAIZ2XP/mn9uogmUCiq2uzzmno+ucctgB9c9otAXPFijwTnOYHnUvvcclnUMMR+6hDW+i1rPXE07GslWQKwN4VicKSdC2W5KDEc2xjRbpeVodky6183uVIqB/6cy1t4Q7PiBoRpAQUa9pZBZCUuSQoR++bDIdczMP+LoqZ9IgLEkqneUwEJ4Tv/D1XPGDRyX01Vc86RT/9HAbaPGocpjxH+C/27YgLIZwvMKspd/w4ohJsXKbXf3p+2cRO37vayOt8SXV9l35f5wA4iBM+Pz/EqRZ7iHD/DUnh2MrLeWLmOIGUtjjgIs8r6n/1N3c+3Hv6DdlBnyttDAQX1EPW6rFdxmO4z8/bHdugPrYNsYeJhDWQru2gaQ/zTCgSRucUjjpCQzW0C1AGfp9IkiQ71s+uQJhGrnAkwBrf8qPjsKy2EzooMvQ0K2wPQ+W+ibUjmcThAu8A9wjx0tZDdyTQB8KzoJJvUuphh6V43a5ZWB5PyYbn3ldHBtlzjLno0xWlygvSuf3JHnas="
script:
  - npm test
