branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "Fte9f0CQg4tWs0wIRBOuMKrFkAr7t1JzNSq8qv0BVn9aOAkygn5wfCnjI2QA2EIjFB5OqlMuZM88VitSBjlcGqfv+ggpdPuxWxKNL+IKQsO2YJeB+qWG+VGaGkAzS2XD62b4BZvXVExUYiZ8GHAPebM1cM/HWkBR92gaCaW8XRwI/jX+Q8BHkv5fRyZE/ACsyCxzBbOVaj+36ydOQv5Nz4tYohY1Y70fYmNslYTc6ZvOZiz42HeW/rX7N5JtUz3+Q/CC3lnwaBo98O5b/Fg5VIr6X34NY9940DaQx0TCctAXcZsuRqayx0O8eAsgGnLvIhkXBOOiTzPap2Cbvmal7u6h6dGuYnLCYBOWu8P5qxmF/8xv3IH36raUF6W8xtAUrUwcDWrOzJ4WAaSACmpBYrqdyar9Bh7j4BGDXTIj2xOT2PUOxy1DIkdp1+3Fxm8lcPCfEozV1ZYZUQ6Lvi5qzNuR1Sdt3Kv05lbpAAtoiMWtAWJmNNTNgLO+MNodPBpw2Yzgi90gO1MJ5xnndsUozarCK9HW0UtWTXISak8RibvpGCoLIAopis7gE8AtxySrrydyPIFh7DFF9+h6znmEu3hsC9m5t1YZiMyI6AMopjXo+yaaw6hf4pPzsGWkyqsJeVDILEEAGgS7yLrR3AUceppJI0LLUpiUOcGRe/KkPys="
script:
  - npm test
