branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "YpjmsRWFK43JC2o9ZJ5P9MpqR1FQ1F8fJaMYf6uy7zQC5GyML6yHsF3yCNIbvM5pgW+uZ95tQelIcKVBCKCTJuJIGi6P0yHTs1GPOvNHJ3+1/fgdkqhZY0fF0ndY1+qDvukiNO0G4rbOGfG+crZHnapx5t2tu375/g1JpcRy1RRaNZlgiVW/wBRGsyUR8bkps3DhXlsTnIPii1dSvUNd+zADljw/uJUs6v09UNoRmpDAkAxHfqDbSY5sC3dazKvgFA+FKGkyww7dxQcC+e9gf0PBQ95so+Ma4rNhZWkNxo1MN3PDXUoKfXRogFbXziP4s3ooS8/YZ4hAhcCYIF03L16sFy8fRyNB3n3+ncp8vEIQtHE0+wI6G8kEzNclCVl02ufa/xt8lgut3c2yAZExrMtyUirk1HnZZtMU5gCP++zrrObv9R4IriL8hWCM9zuQEC+BiUJaEKLg8mtsQUFeJw0Q42pp3glR9DPob9LmraIKa4dJEXqAFizvg0ka2FbfikOVmyvz/8OxdScHyUMAhFNVY9r7S84vImmsR7rhL2gTTPagQVV+yX1JJ2q/LC0yG5Uzf/fQvDF5F31NKQG9GsocsT96Cy4qwXlXg3jygjXkd3QCyhITRYnXg8M5VsMR6vOewYWBFlW+Et39hOTp1rTx3V8pNeZT4VfO7Ua3pWA="
script:
  - npm test
