branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "YbM9xYqcNmT7g9x+E7AR9YZ6ohXFKC+o2F0ZqMn0AG+s48y2j8+1fsh4JjTpY0bVtXtPYh+W5U9/d8j2o4GCuCN9NjhAYqPjb8YqrOASzvRNzbpRurvMZbTXkzmVfL5SB//tL/N+2qPahB/Z+g7n/24X//D1FSOXWzBIIB0AMGDGPNH1y4SgC1q4bw6QXu8xHa0weCyUxiHvqcnFL0A9DEKB9CXvQa0lIpcjexN6mtCYcyNetK+qnDuqbjlsAGPlqObSvy4oNTzXU8andAAGXSIxGJuIlxMFwWCVKALtyzJOUtYQjdX+OHeNJFvWaEgbJaghA/OC3SqE7Bwt0xVmh2D582Dr1YlOv07EEhJmjFygkF9OCDsVc3NQvOZg2q44YYfVPcM7fsKNTupww9dG0MJsvpcSkwQd/UqHT74fJzh8CXyINF3ZYj1eYLAXQ0gx3g7/nWgkPJN8xwNXj0ZfVXRrOWANVkYYdT7EKseEaUmcsPfyIJA3ZtRGj4NJqXioyhm94u/79D41PMEYkvgy8ej7nUlf/YCWeAII+y5en44rqN8AS7NtQvoaBO0cuDTFjT4d9szTD024eHrSDg0zkUNQ8tg9mJzJCiTNTxTc3XNahcirYL08scdVxenvNNO9hcf/eP2iN+U2FTN34FWxTKj5LyEewRUtsYpwTATg4Ik="
script:
  - npm test
