branches:
  only:
    - master
deploy:
  on:
    branch: master
    condition: $NEXT_RELEASE_ENABLED
  provider: script
  script: bash support/deployNextFromTravisWrapper.sh
  skip_cleanup: true
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "J7vhVB8FZzyyZSBzfML0WRmar1lvX2Iseb4jJhXpUrGR021JnfknSOZhyWupgRDoHtmy/HSqE8WPNWC6R0eoijKIhCNLKtVkTbi21ylXTTfnBeRNR8DEkI2tYnpyGjy+S3pnC0xPQdlpaEIYY0iyv2U8E4LpyOqJKNfPwmXofWJWYPykviHdTG1cBvNbPAoRCl/RmN4akO8/YVCFWr95JVfXNruK2KQLMCTzUCj8AGHFFuA3WOooEz7WByIVY7vrkhidKrDcMA4TbigiPOSnMIsRmnILdLXLRd+ioPSe9fDek3rZHojQZhAwta2SfNJSGJ9XBtSTVoBjBd8df/SNCtpV8x4oP+R91GSDNYdsZMhKpJuQaHWFIgAbYpTIBG7f5RYaEE91LPK6AaMVJVahmlVQ3bTQZyqi3GNHhiivobjJtMVFyC7O1ENzWCjhbFyOhYD6KNtrvuvaW5bpUEUcHCCD6xZtvIvRKoBaU4Sk701TJXn/P3dYGwxg3yobpYC5xyEGwnHDHxm/EddMrk5VDdYOKmukyRd9Ugjrog899mvslqN3c+c/D5mKR0EUe2IvEvqS8FdU/T2FN0akd5kL0F3Ieu8CkPh9JBm8G356MJpWpH9e0oeX6qy5QcQnPUelTnnr6/G9LwUnkHE1B7D2La5B+PTUwNxoPK9K9o2UyIA="
script:
  - npm test
  - npm run test:storybook
services: xvfb
