branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "GipZXbrRO+LaoT6nHIpQnLw0Q3W2W/8WDmA3EYmswLttfrZztsFnkWFKHBmm9b9CxLOO7VqmWEOFYvKXetCOF0LNUAyvPAfYxBO/nOFuV21Si0ERKT3m4NL7XyLixZnQ5vK4TF8w+d88OoejElbuBZDG6ezgIpqJHx/PccI6gD8v2Nnz/F0IjQCd4LMM8jbjb1stVgHNuGPovXYoIklcUNr4GZcFsob5e2kAeMBQt9b8VS6kx0xidQml6gT53QWZRtQKVZZTbgDmf7+7ewol5A912zSt6WtJlyz5AmPny793Z+PjL6ctu+LmunFXAaOlEawSQq1rpzbTjQwl9S3XdEbY/t77R2lk3iTp20pes8/WJHAzAW7717vGluYEX3LdQOdYBhY3MKc9Xyk5oxWEIR+eJfj0zK6n3RGtrH8jGKry23IoazhHiCIrMtVDps9k5Lw/LYH62RBC/3qb8tdyQGjHqfRW1mNWjLgjluHiJhjFp5TqBLx9rMeK+bOPVWedlUo3utDixlYp+ryu2HVSdwKC+LMemPG5A3A17R9//JyQUh8Lay0WqfCwr+7J/4wOMZyQtTB18vtF6KHKiN4rnpyYLU3s4OHP32odxyhJIoWwbU5xJPGJbguUaru+6GMnDnGE+gUXi17/M4LScb3xUrxqaL8V6EXoZPt9OAiCG+U="
script:
  - npm test
