branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "ScZNPlq18cwpEsN5DN/RhE859/rjSTAvg/z58hva16j6NDFElVIRNWvusQ1Nc/CD499sRcTT7ORazfBfmsWjubD20bdMR0IXT1BgA8Avk9DJPWN+481VQR92ZN3R1NSoDMBDby5Hv+I+3CdnCnmmpTVOntHfbVrO/opwqYfhcMG6SleIZWpCsf02nruAYu7KzPWGoxTv5Ttb+p6hSXHpiT06qtzG1X6l3KNVApWHz3sYgZfcYGtBxvAkhVYl6Cs1GHKpvAwI1NFvUms+NVWoqCMd0XYOrL1s3d5m05DG+Fvj94QBT1zw3pAHRhOJzQss1wyYu9gR7UR5uwzCOFetuhERdlkJ38vDrKOSIAoG/uOszViczqjuXSerhqYjAXc7KMjMo4l4N/PLjY+EOqpAwX0MMn36GxeuaauPmjOKIQmtD70KvZ7iOmm7hDa8bSQCNcGqam8dGSUTPA9CckBk5xqWjAKZrSAkElaubQwX7cozbYQ5vRXEiKSFcPlPkgqWcMDz2mNoqqf3CGPRdDaFznBg7Fen3Gaj3FWpFS8FfVdQuD2KQb9QrDfQh9teBGUV+lVo54QVAwlGSvj+lQl99k28bjEVWXoO0Y7cPPfG+cvgS/skVR5jNTmF5q+/omwptcb0F1oxXeVRcuafDzVN+FMx0GDt3yxynvipqGMPypw="
script:
  - npm test
