branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "QNgtdFPrrKKA85XryuFyCyPlh4s/3RxJuXM3XTDx6wQZJBcu8Wyj/GQOXu0DGxA3hxfenYzRaOS5WI2NMxg2tgOAOU5Bv6uw5mPOTat/k11vH29ji2HA7nOOjZPW3fWmtnDzjVqF7Kkj0/noGD+oy3mUUDlqd/33rJMHSbiU6CgM9dYEcRj7Nl/diLmNqGc66G91Plqmc/8royHrUOs27kblXYmHEdBwOT9iSCy4FxSLBD4++NgoBEdPfR2VLEvPA9JwVR/YqmGyesigSE3yZ4jH+MZteXn84RZxQHldOxHtX5clzwyNv2/ebrdNZhhX5KQLV5N5jA5BjCaRzg9bKx3YJMnAs9At4GMWbSZjoOTC2RC/YLP0bJo16l0jj39JnezYxJ6+AFxELjVl/yI6vXoUGWkP67uKBbLbNp2qYyO85w1TyK/MP2TwD1XiM5SI6Fh79frpsDSw39Z8Ehf3wWpnsz1xK7LsljgzdC0znbkMgHn05ftwDs/kIWZm2qoiIpVJvUEL/2SYCipKr8/KyLASY/UZ9Blo6dhWRvlS9S8mFZjCiIpRw96dGN8Z4AFgwDvarbPRRI+eT1bqxCY0RXsqAVrPMCKHTcjnwP26onRhVxOOHKIcDhowG3x4nRbaiMDd8DuALBCwOg4xtgqODt4964BaoPv3wh/yB/30Qog="
script:
  - npm test
