branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "If5nQbNxF0AYfLzEH/DSqe69iAUKReFBpTmvFJzCieo6RqK50o7RNSixkDWT4W5HeG4LZ5T4mBNRtKz67nfhc9JRhTS6H1hdA1OMcmuS8Sp+NgsA8vA4X4JPfPZMb5mUXAWCMpjJgG7p3DKpfhesF1kCvZs3vwLtlAisU5gFphQwED8vCxGpFqEyL/2L+tkG2Xbkx2DSJfttU6DTCc6N5mIamVFAjjHrKZvgQoiyLaMEIxTK82QH9oUvS6nh20RCH0ZkDf4VPvl2s8RoqbL8lvpwZk4WC93n64BVziaddKiH0QOQHbp1HzclfG1GFfp2QbcJmNyBSSM9owNcn0mWH+DPuXrrTsvilIM7KikGcq+9SIj7x4zrn0LPqZFSu07E9YgWd99fxojdmrWqB+NHY9G5NL8j238wRiSPunxbd3BPNrxeMJBVT5AIXkn//HwNZDF0owHxBEPOuX1wEBh7RybPwmTkmS4Eurq5LTUfKGk2T+8OjgFb+lD+c6SpBx5+WSFPw++T6b8naZ9B1J9FHIabYU4JU46aoZG8jXHDGDINz4s9josrBBqszWri0UMkvPxbqkfGa0T05ANT1hTv5V55q1xr2fM372TL5RmMUWVOiYFtZt30H6zbpjdVejlOuR3Oc7A3Q0jh8F2FOPpfj7LJt4mojEEs7L/c28prlPQ="
script:
  - npm test
