branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "hKfUvNV5Hzh7UcQfEjbhv5yt30aU70iENTGv/oOpCEssU3Wg1vPrpqTf5Esdj6cybmGyh5p4xF0qzaTG/4vraN6p+0i1KG1m9nbnHjOaXCuPAUwJJ/TmkdfNwp7D1LFCBHuJFNjr0htKIcgS8FaKxm0bpY5gBdnMm7WgEjYaI51wGNAZ5ip53nf8Gnyomh1/GBxkqVva6IbbYTvglYNfKqs8o1cmC0t9fyUOt23qvqHYQnafatWH3ZCBy/6QDp/6kV/s157lH+v2N6fvI55OO5JFj2++bqYfd6e4cTewrAtFIHfPQQ04oVYJ93n/m1VVd6QpPks0fPLobvWcw/Z+uT2N7dDyALOkZUdC9nnHGk/Ch0eoW/fhlUymzqRdvCQ5HowfdsmPk70eFQQiEqt+ZWcTlSUeY59RLnoRRsr9yQghlHv+dhwib29GS3wdL+nk2XLbaie+FnpzvSZWc/BY+fsYvH8e7rkofHmNP3N8i2medCTvNf8E7Nep00u+6/z1//bKEPcXtfBOw9mP4zbwX1zcIIKVuzhJPn6v334gw7hdoCs2Iav0v3zeo9UOq9xb81/j+nCaNAfHLVgxtDfx5eAFFByTNNb0SFot8QBa1B+wJFkYXM+nJWFgOBQmSnd0q+gb/4r514man7Y2nuJHx2qUaxIULsq/dQwL3QXKaGU="
script:
  - npm test
