branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "T06MotoWDhEk2sc/bv7q7Z+Z/N5oYYOoFG7rO2YbgVXdJHw1dS92WVe7eTT+TAdtB1jk85M6IlzA52dMuS1Ev8N1uhVtbub51+amMeFfjnAOfBRYDAHrqlTk8uMssjyqI3ZZos6Yaay+BeFLNBY+k5chikj5a5S6+lR/F+W01VwJxWngHr7JSdruCX/aDd1M8Hn7zIEnODSzsFCDYSkduFVjsgMbItPP+AwftGTL7UUV+rCAeXwbu5AeT/SEvLzWNP3Irr57MVhRtfGZT76YFRICb1oRyCOUe9YBoZaNr4awewb5XowNwLnrotXL9DYQkN+N0d7/OKsAjKs8/RNoQeyftmBO5y2MRGitmhBdOer3E2PQgjgYoinWwxcGXhsauRINg9C7z/UguMyTya8v8ziJg592INXIq469IRqP7PikSlVeXlvaCtJWDIIr7Luv4JiIOqHQ+bu9BMIKqQxXyS7xoXfjKgdWX0dQVo6bn5pi3hyJNNywCf2MyEtojxXvDaU1yiTd5fRNbsqm2jp0r6+m1L1DbNEhOtOR2DSVvbtw4kRxNjTejBCPnQWgklurIeIztV1qF+26JGIutQWXtf+UYmKnTBgiR8HX5YVGQDRL6hVgUI/E5buDoit3twnZyUuMJZgJHSY5IcC+pgjQIY+YDOPXsbRvAOYX8K6uokI="
script:
  - npm test
