branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
notifications:
  webhooks:
    secure: "XGfkd5syIbHyufAexrUMjXFpljEMCTqVdYETawYk1lXOVWpp8V0snqtDVb5C35JJhoLhfUYWsqn9OVCnQL4Kik1EQUvVNA90B0sMGAt2QXkeIPd8UXgXoejElvJCO30UWqyUWPOiQt/FxKeCJXQX0UtZ7IXaIIyyqCTxgc063OBgz0Mw+ybWap/reN2Znb6OBrnbWqwiCGZOqJfha070ebEvbJwj5v6EaYRnBw59vwdy5q1+wTmAS1WDWyt6DX+SgAzWlPaeqwLwnhvMXqW6tn37u9zDxTKY5PUJK6HI4QYwyU1l6R6A+5s25ch7UgKKl4QMPKkqPKJUnP1VajBBZ8doX5tl77ZI+MhlCFPp1uMhhU5UIyemev7GI1cGcP8stxyCLLJ6Lwe1xGSA97O6sIdt03Ub/eZIN1kkvzmEfVl0E9tuitzhL6a2VpIqwmRSt7OMOrtuzD6A0I5hy2gT6Fqr4YuR0KjWlIIKYiu8hGGCi/zIM6TfDegcOzJhC8HY9UzYY3Bd+NG1kxI3z9d9iTT+aUsjz104ZmpVqdbCDfFatlFdIVADt73U2FJrgI5YavTp2lbsfxFR37X8Bfy7PY1Oxy5ojYJt9rLBITYFAvzlQvDP1+dr2BYlajd7hkdJY+ZdxggfK0y7bC9kM/COcWf8dedxuLT65a23YIpjBH8="
script:
  - npm test
