name: Enhancement
description: Request for a feature to be added to an existing component
labels: ["enhancement", "0 - new", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        - Please [check for existing issues](https://github.com/Esri/calcite-components/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction to the existing issue instead of creating a new one.
        - For support, please check the [community forum](https://developers.arcgis.com/calcite-design-system/community/).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the requested functionality?
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: Requirements, desired new behavior, etc.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Relevant Info
      description: Dependencies, blockers, helpful details, etc.
    validations:
      required: false
  - type: textarea
    id: component
    attributes:
      label: Which Component
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example Use Case
      description: Code snippet, link to a similar product, etc.
    validations:
      required: false
  - type: dropdown
    id: esri-team
    validations:
      required: true
    attributes:
      label: Esri team
      multiple: false
      description: If you work at Esri, please select your product team. Otherwise choose "N/A".
      options:
        - N/A
        - Calcite (dev)
        - Calcite (design)
        - ArcGIS API for JavaScript
        - ArcGIS AppStudio
        - ArcGIS Business/Community Analyst
        - ArcGIS Dashboard
        - ArcGIS Developer Experience
        - ArcGIS Enterprise
        - ArcGIS Excalibur
        - ArcGIS Experience Builder
        - ArcGIS Field Apps
        - ArcGIS GeoBIM
        - ArcGIS GeoPlanner
        - ArcGIS Hub
        - ArcGIS Indoors
        - ArcGIS Insights
        - ArcGIS Instant Apps
        - ArcGIS Living Atlas
        - ArcGIS Map Viewer
        - ArcGIS Marketplace
        - ArcGIS Mission
        - ArcGIS Network Analyst
        - ArcGIS Online
        - ArcGIS Scene Viewer
        - ArcGIS Site Scan
        - ArcGIS StoryMaps
        - ArcGIS Survey123
        - ArcGIS Urban
        - Marketing UI
