name: Add Esri Product Label
on:
  issues:
    types: [opened, edited]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        with:
          script: |
            const { ISSUE_BODY } = process.env;
            if (!ISSUE_BODY) {
              throw new Error("Could not determine the issue body")
            }

            const productRegex = new RegExp("(?<=### Esri team).*", "s");
            const productRegexMatch = ISSUE_BODY.match(productRegex);

            if (!productRegexMatch || !productRegexMatch[0]) {
              throw new Error("Could not determine the Esri product")
            }

            const product = productRegexMatch[0].trim();

            if (product && product !== "N/A") {
              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [product],
              });
            }
