name: Verify Install
on:
  issues:
    types: [labeled]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        env:
          ISSUE_VERIFIERS: ${{secrets.ISSUE_VERIFIERS}}
          CALCITE_DESIGNERS: ${{secrets.CALCITE_DESIGNERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/assignForVerification.js')
            await action({github, context, core})
