name: Move Issues To Current Milestone
on:
  workflow_dispatch:
    # schedule:
    # - cron: "0 9 * * 1"
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/changeMilestone.js')
            await action({github, context, core})
