name: Close Completed Milestone
on:
  workflow_dispatch:
  # pull_request:
  #   branches: [main]
  #   types: [closed]
  # issues:
  #   types: [closed, demilestoned]
jobs:
  close-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/closeMilestone.js')
            await action({github, context, core})
