name: "Deploy Storybook"
on:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - name: Deploy storybook
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npm ci --legacy-peer-deps
          npm run docs
          npx storybook-to-ghpages --existing-output-dir=docs --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.ADMIN_TOKEN }}
