name: Build
concurrency:
  group: deploy_next
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: e2e test
        run: |
          npm ci --legacy-peer-deps
          npm test
      - name: storybook/next deployment
        env:
          NEXT_RELEASE_ENABLED: ${{ secrets.NEXT_RELEASE_ENABLED }}
          # https://github.com/storybookjs/storybook-deployer/issues/77#issuecomment-618560481
          GH_TOKEN_FOR_STORYBOOK: ${{ github.actor }}:${{ secrets.ADMIN_TOKEN }}
        run: |
          if [ "$NEXT_RELEASE_ENABLED" == "true" ]; then
            if npm run util:is-next-deployable; then
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git config --global user.name "github-actions[bot]"
              # deploy storybook, but still release next if it fails
              { npm run build-storybook && npx storybook-to-ghpages --host-token-env-variable=GH_TOKEN_FOR_STORYBOOK --existing-output-dir=docs --ci; } || true

              # remove the build to docs after storybook deploys to gh-pages
              # if there are changes the git sanity checks will prevent deployment
              git clean -fd && git reset --hard && git checkout master && git pull
              npm run util:deploy-next-from-ci
            fi
          else
            echo "Next release is disabled"
          fi
      - name: notify teams
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI_BUILD }}
          show-on-start: false
          card-layout-exit: complete
          timezone: America/Los_Angeles
