name: Deploy Next
concurrency:
  group: deploy_next
  cancel-in-progress: true
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
        env:
          NEXT_RELEASE_ENABLED: ${{ secrets.NEXT_RELEASE_ENABLED }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ env.NEXT_RELEASE_ENABLED }} == "true"
      - run: npm ci
      - run: npm test
      - run: | # gh env vars dont work in node
          npm install dotenv
          touch .env
          # adds a dotenv import to the top of the next deploy script
          echo "require('dotenv').config({ path: '.env' })" | cat - /support/deployNextFromTravis.ts > temp && mv temp /support/deployNextFromTravis.ts
          echo GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .env 2> /dev/null
      - run: npm run util:deploy-next-from-travis
      - uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI_BUILD }}
          show-on-start: false
          card-layout-exit: complete
          timezone: America/Los_Angeles
