name: Label PR
on:
  pull_request:
    branches: [ master ]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"