name: "main"
on:
  release:
    types: [released]
jobs:
  move_to_next_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: move to next milestone
        uses: jcfranco/actions-milestone-sync@aed539478f3c52958c3f5e22bd6d4a185532d855
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

