name: "main"
on:
  release:
    types: [released]
jobs:
  move_to_next_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: move to next milestone
        uses: jcfranco/actions-milestone-sync@1e6c074cad4d8d627128f25a46d72eced6f5da45
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

