name: "Move issues/PRs to next milestone"
on:
  release:
    types: [released]
jobs:
  move_to_next_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: move to next milestone
        uses: jcfranco/actions-milestone-sync@ffa4273c5060e42e3cbcf2a12958244fb04c05ab
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

