name: "Move issues/PRs to next milestone"
on:
  release:
    types: [released]
jobs:
  move_to_next_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: move to next milestone
        uses: jcfranco/actions-milestone-sync@45fb8180b4ec0f176a26379ae7528b3fffdccf09
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

