name: 'Need Info - Verify'
on:
  issues:
    types: [labeled, edited]
    branches: [master]
  issue_comment:
    types: [created, edited]
    branches: [master]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/need-info-action@v1.3.1
