name: "Need Info - Close"
on:
  schedule:
    - cron: "30 1 * * *"
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          days-before-stale: -1
          days-before-pr-close: -1
          days-before-issue-close: 5
          remove-stale-when-updated: false
          stale-issue-label: "incomplete issue report"
          close-issue-message: "This issue has been automatically closed due to missing information. We will reopen the issue if the information is provided."
