name: "Need Info - Verify"
on:
  issues:
    types: [labeled, edited]
  issue_comment:
    types: [created, edited]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/need-info-action@v2.0.0
