name: 'Need Info - Verify'
on:
  issues:
    types: [labeled]
    branches: [master]
  issue_comment:
    types: [created]
    branches: [master]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/need-info-action@v1.1.0