name: "Notify CC Designer Leads of New Component Issue"
on:
  issues:
    types: [labeled]
jobs:
  notify-designer-new-component:
    if: github.event.label.name == 'new component'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          designers: ${{secrets.CALCITE_DESIGNERS}}
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/notifyAboutNewComponent.js')
            await action({github, context, core})
