name: Release Notification
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        if: contains(github.event.release.tag_name, '@esri/calcite-components@')
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"@context": "http://schema.org/extensions", "@type": "MessageCard", "title": "${{ github.event.release.tag_name }}", "text": "🚀 <code>${{ github.event.release.tag_name }}</code> released! Check out the [changelog](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/CHANGELOG.md#changelog) for more info. 🚀"}' ${{ secrets.TEAMS_WEBHOOK_URI_RELEASE }}
