name: PR Bot
on:
  pull_request:
    branches: [main]
permissions:
  pull-requests: write
  issues: write
jobs:
  assign-author:
    if: github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/actions/assignPullRequestAuthor.js')
            await action({github, context})
  label-type:
    if: github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/actions/labelPullRequestWithCommitType.js')
            await action({github, context})
