name: PR Merged
on:
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  milestone:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@v1.3.1
