name: Auto Merge
on: issue_comment
jobs:
  merge:
    env:
      PRIMARY_CONTACT: ${{ secrets.PRIMARY_CONTACT }}
    if: |
      github.event.issue.user.login == 'github-actions[bot]' ||
      github.event.issue.user.login == github.actor ||
      env.PRIMARY_CONTACT == github.actor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: merge
        uses: Goobles/gh-actions-merge-command@v1
        with:
          allow_ff: false
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
