name: Screener
on:
  pull_request:
    branches: [master]
  # need to run on the base branch when merging to keep the baseline state up to date
  push:
    branches: [master]
jobs:
  screenshot_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: install dependencies
        run: npm install
      - name: run screener check
        env:
          SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
          COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}}
        run: npm run test:storybook || true
