name: PR title is not truncated (...)
on: pull_request
jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: "^[^…]+$"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
