name: Release Notification
on:
  release:
    types: [published]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        uses: actions/github-script@v4
        with:
          script: |
            const release = context.payload.release
            if (!release) {
              console.log("No release found")
              return
            }
            core.exportVariable("RELEASE_VERSION", release.tag_name);
      - name: Teams channel notification
        uses: FTsbrown/msteams-action@v1.0.1
        with:
          TITLE: ${{ env.RELEASE_VERSION }}
          BODY: "🚀 <code>@esri/calcite-components@${{ env.RELEASE_VERSION }}</code> released! Check out the [changelog](https://github.com/Esri/calcite-components/blob/master/CHANGELOG.md#changelog) for more info. 🚀"
          MS_TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK_URI_RELEASE }}
